image: maven:3.9-eclipse-temurin-19

stages:
  - lint
  - test
  - build
  - deploy

cache:
  paths:
    - .m2/repository/

before_script:
  - mvn --version

lint-job:
  stage: lint
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
    - if: '$CI_COMMIT_BRANCH == "main"'
  script:
    - echo 'Compiling'
    - mvn compile

test-job:
  stage: test
  only:
    - merge_requests
    - main
  script:
    - echo 'Testing'
    - pwd
    - mvn test
    - ls
  artifacts:
    reports:
      coverage_report:
        coverage_format: jacoco
        path: target/site/jacoco/jacoco.xml
      junit:
        - target/surefire-reports/TEST-*.xml

build-job:
  stage: build
  only:
    - main
  script:
    - mvn package -DskipTests -B

deploy-job:
  stage: deploy
  only:
    - main
  script:
    - echo 'Deploy'